/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangProtectedRouteRouteImport } from './routes/$lang/_protected/route'
import { Route as LangAuthRouteRouteImport } from './routes/$lang/auth/route'
import { Route as LangProtectedProfileRouteImport } from './routes/$lang/_protected/profile'
import { Route as LangProtectedResetPasswordRouteImport } from './routes/$lang/_protected/reset-password'
import { Route as LangArticleIndexRouteImport } from './routes/$lang/article/index'
import { Route as LangAuthErrorRouteImport } from './routes/$lang/auth/error'
import { Route as LangAuthForgotPasswordRouteImport } from './routes/$lang/auth/forgot-password'
import { Route as LangAuthLoginRouteImport } from './routes/$lang/auth/login'
import { Route as LangAuthRegisterRouteImport } from './routes/$lang/auth/register'
import { Route as LangFeedbackIndexRouteImport } from './routes/$lang/feedback/index'
import { Route as LangArticleIdIndexRouteImport } from './routes/$lang/article/$id/index'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProtectedRouteRoute = LangProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthRouteRoute = LangAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProtectedProfileRoute = LangProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LangProtectedRouteRoute,
} as any)
const LangProtectedResetPasswordRoute =
  LangProtectedResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => LangProtectedRouteRoute,
  } as any)
const LangArticleIndexRoute = LangArticleIndexRouteImport.update({
  id: '/article/',
  path: '/article/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthErrorRoute = LangAuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => LangAuthRouteRoute,
} as any)
const LangAuthForgotPasswordRoute = LangAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LangAuthRouteRoute,
} as any)
const LangAuthLoginRoute = LangAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangAuthRouteRoute,
} as any)
const LangAuthRegisterRoute = LangAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LangAuthRouteRoute,
} as any)
const LangFeedbackIndexRoute = LangFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangArticleIdIndexRoute = LangArticleIdIndexRouteImport.update({
  id: '/article/$id/',
  path: '/article/$id/',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/auth': typeof LangAuthRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/profile': typeof LangProtectedProfileRoute
  '/$lang/reset-password': typeof LangProtectedResetPasswordRoute
  '/$lang/auth/error': typeof LangAuthErrorRoute
  '/$lang/auth/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/register': typeof LangAuthRegisterRoute
  '/$lang/article/': typeof LangArticleIndexRoute
  '/$lang/feedback/': typeof LangFeedbackIndexRoute
  '/$lang/article/$id/': typeof LangArticleIdIndexRoute
}
export interface FileRoutesByTo {
  '/$lang': typeof LangIndexRoute
  '/$lang/auth': typeof LangAuthRouteRouteWithChildren
  '/$lang/profile': typeof LangProtectedProfileRoute
  '/$lang/reset-password': typeof LangProtectedResetPasswordRoute
  '/$lang/auth/error': typeof LangAuthErrorRoute
  '/$lang/auth/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/register': typeof LangAuthRegisterRoute
  '/$lang/article': typeof LangArticleIndexRoute
  '/$lang/feedback': typeof LangFeedbackIndexRoute
  '/$lang/article/$id': typeof LangArticleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/_protected': typeof LangProtectedRouteRouteWithChildren
  '/$lang/auth': typeof LangAuthRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/_protected/profile': typeof LangProtectedProfileRoute
  '/$lang/_protected/reset-password': typeof LangProtectedResetPasswordRoute
  '/$lang/auth/error': typeof LangAuthErrorRoute
  '/$lang/auth/forgot-password': typeof LangAuthForgotPasswordRoute
  '/$lang/auth/login': typeof LangAuthLoginRoute
  '/$lang/auth/register': typeof LangAuthRegisterRoute
  '/$lang/article/': typeof LangArticleIndexRoute
  '/$lang/feedback/': typeof LangFeedbackIndexRoute
  '/$lang/article/$id/': typeof LangArticleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$lang'
    | '/$lang/auth'
    | '/$lang/'
    | '/$lang/profile'
    | '/$lang/reset-password'
    | '/$lang/auth/error'
    | '/$lang/auth/forgot-password'
    | '/$lang/auth/login'
    | '/$lang/auth/register'
    | '/$lang/article/'
    | '/$lang/feedback/'
    | '/$lang/article/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$lang'
    | '/$lang/auth'
    | '/$lang/profile'
    | '/$lang/reset-password'
    | '/$lang/auth/error'
    | '/$lang/auth/forgot-password'
    | '/$lang/auth/login'
    | '/$lang/auth/register'
    | '/$lang/article'
    | '/$lang/feedback'
    | '/$lang/article/$id'
  id:
    | '__root__'
    | '/$lang'
    | '/$lang/_protected'
    | '/$lang/auth'
    | '/$lang/'
    | '/$lang/_protected/profile'
    | '/$lang/_protected/reset-password'
    | '/$lang/auth/error'
    | '/$lang/auth/forgot-password'
    | '/$lang/auth/login'
    | '/$lang/auth/register'
    | '/$lang/article/'
    | '/$lang/feedback/'
    | '/$lang/article/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_protected': {
      id: '/$lang/_protected'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangProtectedRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_protected/profile': {
      id: '/$lang/_protected/profile'
      path: '/profile'
      fullPath: '/$lang/profile'
      preLoaderRoute: typeof LangProtectedProfileRouteImport
      parentRoute: typeof LangProtectedRouteRoute
    }
    '/$lang/_protected/reset-password': {
      id: '/$lang/_protected/reset-password'
      path: '/reset-password'
      fullPath: '/$lang/reset-password'
      preLoaderRoute: typeof LangProtectedResetPasswordRouteImport
      parentRoute: typeof LangProtectedRouteRoute
    }
    '/$lang/article/': {
      id: '/$lang/article/'
      path: '/article'
      fullPath: '/$lang/article/'
      preLoaderRoute: typeof LangArticleIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth/error': {
      id: '/$lang/auth/error'
      path: '/error'
      fullPath: '/$lang/auth/error'
      preLoaderRoute: typeof LangAuthErrorRouteImport
      parentRoute: typeof LangAuthRouteRoute
    }
    '/$lang/auth/forgot-password': {
      id: '/$lang/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/$lang/auth/forgot-password'
      preLoaderRoute: typeof LangAuthForgotPasswordRouteImport
      parentRoute: typeof LangAuthRouteRoute
    }
    '/$lang/auth/login': {
      id: '/$lang/auth/login'
      path: '/login'
      fullPath: '/$lang/auth/login'
      preLoaderRoute: typeof LangAuthLoginRouteImport
      parentRoute: typeof LangAuthRouteRoute
    }
    '/$lang/auth/register': {
      id: '/$lang/auth/register'
      path: '/register'
      fullPath: '/$lang/auth/register'
      preLoaderRoute: typeof LangAuthRegisterRouteImport
      parentRoute: typeof LangAuthRouteRoute
    }
    '/$lang/feedback/': {
      id: '/$lang/feedback/'
      path: '/feedback'
      fullPath: '/$lang/feedback/'
      preLoaderRoute: typeof LangFeedbackIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/article/$id/': {
      id: '/$lang/article/$id/'
      path: '/article/$id'
      fullPath: '/$lang/article/$id/'
      preLoaderRoute: typeof LangArticleIdIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangProtectedRouteRouteChildren {
  LangProtectedProfileRoute: typeof LangProtectedProfileRoute
  LangProtectedResetPasswordRoute: typeof LangProtectedResetPasswordRoute
}

const LangProtectedRouteRouteChildren: LangProtectedRouteRouteChildren = {
  LangProtectedProfileRoute: LangProtectedProfileRoute,
  LangProtectedResetPasswordRoute: LangProtectedResetPasswordRoute,
}

const LangProtectedRouteRouteWithChildren =
  LangProtectedRouteRoute._addFileChildren(LangProtectedRouteRouteChildren)

interface LangAuthRouteRouteChildren {
  LangAuthErrorRoute: typeof LangAuthErrorRoute
  LangAuthForgotPasswordRoute: typeof LangAuthForgotPasswordRoute
  LangAuthLoginRoute: typeof LangAuthLoginRoute
  LangAuthRegisterRoute: typeof LangAuthRegisterRoute
}

const LangAuthRouteRouteChildren: LangAuthRouteRouteChildren = {
  LangAuthErrorRoute: LangAuthErrorRoute,
  LangAuthForgotPasswordRoute: LangAuthForgotPasswordRoute,
  LangAuthLoginRoute: LangAuthLoginRoute,
  LangAuthRegisterRoute: LangAuthRegisterRoute,
}

const LangAuthRouteRouteWithChildren = LangAuthRouteRoute._addFileChildren(
  LangAuthRouteRouteChildren,
)

interface LangRouteRouteChildren {
  LangProtectedRouteRoute: typeof LangProtectedRouteRouteWithChildren
  LangAuthRouteRoute: typeof LangAuthRouteRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
  LangArticleIndexRoute: typeof LangArticleIndexRoute
  LangFeedbackIndexRoute: typeof LangFeedbackIndexRoute
  LangArticleIdIndexRoute: typeof LangArticleIdIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangProtectedRouteRoute: LangProtectedRouteRouteWithChildren,
  LangAuthRouteRoute: LangAuthRouteRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
  LangArticleIndexRoute: LangArticleIndexRoute,
  LangFeedbackIndexRoute: LangFeedbackIndexRoute,
  LangArticleIdIndexRoute: LangArticleIdIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
